<?php
/**
 * @package    Leytech_OrderShare
 * @author     Chris Nolan (chris@leytech.co.uk)
 * @copyright  Copyright (c) 2017 Leytech
 * @license    https://opensource.org/licenses/MIT  The MIT License  (MIT)
 */
?>
<!-- Leytech OrderShare -->
<?php
if (!$this->isEnabled()) {
    return;
}
?>
<?php if ($this->getOrderId()):?>
    <div class="ordershare">
        <h2 class="sub-title"><?php echo $this->__('Share your purchase to Twitter or Facebook') ?></h2>
        <?php $order = $this->getOrder(); ?>

        <?php $_columnCount = $this->getColumnCount(); ?>
        <?php $_products = $order->getAllVisibleItems() ?>
        <?php $_collectionSize = count($_products) ?>

        <?php $i=0; foreach ( $_products as $item ) : ?>
            <?php $_product = $this->getOrderedProduct($item)?>
            <?php $_helper = $this->helper('catalog/output'); ?>
            <?php $_twitter_text = $this->__("I just bought a %s from %s", $_product->getName(), $this->getStoreName()); ?>
            <?php $_twitter_user = $this->getTwitterUser(); ?>

            <?php if ($i++%$_columnCount==0): ?>
                <ul class="products-grid">
            <?php endif ?>

            <li class="item<?php if(($i-1)%$_columnCount==0): ?> first<?php elseif($i%$_columnCount==0): ?> last<?php endif; ?>">
                <?php if ($_product->getImage()) :?>
                    <div class="product-image">
                        <?php $_img = '<img src="'.$this->helper('catalog/image')->init($_product, 'small_image')->resize(135).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
                        echo $_helper->productAttribute($_product, $_img, 'image'); ?>
                    </div>
                <?php endif; ?>
                <h2 class="product-name"><?php echo $_product->getName() ?></h2>
                <?php $_twitter_url = $this->getTwitterUrl($_twitter_text, $_product) ?>
                <?php $_facebook_url = $this->getFacebookUrl($_product) ?>
                <ul class="soc">
                    <li><a class="soc-twitter" href="<?php echo $_twitter_url; ?>"></a></li>
                    <li><a class="soc-facebook soc-icon-last" href="<?php echo $_facebook_url; ?>"></a></li>
                </ul>
            </li>
            <?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
                </ul>
            <?php endif ?>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
<!-- /Leytech OrderShare -->